name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Run make install
      run: make install

    # Runs a set of commands using the runners shell
    - name: Run make lint
      run: make lint

    # Runs a single command using the runners shell
    - name: Run make test
      run: make test

    # Runs a set of commands using the runners shell
    - name: Run make format
      run: make format
