name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test build-Build
      with:
        runCmd: |
          make install
          make lint
          make test
          make format